### ISSUE TITLE
Size mismatch when changing temporal window

### ISSUE THREAD

**Issue by c0d3rman** [blakeMilner/DeepQLearning#1]
When I try to change Brain.temporal_window, I get this error:

```
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/Linear.lua:37: size mismatch
stack traceback:
    [C]: in function 'addmv'
    /usr/local/share/lua/5.1/nn/Linear.lua:37: in function 'updateOutput'
    /usr/local/share/lua/5.1/nn/Sequential.lua:25: in function 'forward'
    ./deepqlearn.lua:195: in function 'policy'
    ./deepqlearn.lua:349: in function 'backward'
    example.lua:40: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x0106c18100
```

It's coming from Brain.policy, where it feeds `tensor_state` into the network without verifying its size.
The state is in turn coming from `Brain.backward`, specifically:

```
local best_action = Brain.policy(e.state1);
```

Help?

**Comment by blakeMilner** [comment]
When and where do you try to change tensor_state? Do you change it directly in deepqlearn.lua or do you try and access it from an external file like test.lua?

**Comment by c0d3rman** [comment]
I access it from an external file. Should I change it directly?

**Comment by blakeMilner** [comment]
Yes, either change it directly or change it before the call to Brain.init(). I'll need to add an API to change parameters and put something in the documentation about changing params.

Let me know if there's anything else.

**Comment by c0d3rman** [comment]
Thanks! I know I was really confused about the inputs to Brain.init - I didn't realize the first one is the number of inputs but the second one is the range of outputs.

**Comment by blakeMilner** [comment]
I understand, the code needs a bit of housekeeping ; )
